<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Controllers\Interfaces\" />
    <Folder Include="Gateways\MongoDbs\Converters\" />
    <Folder Include="Gateways\MongoDbs\Entities\" />
    <Folder Include="Gateways\MongoDbs\Interfaces\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Core\Core.csproj" />
  </ItemGroup>

</Project>
